PR for ROR social media project Second milestone
uchennaanya/ror-social-scaffold pull request #2
Opened 2021-03-25 12:40 UTC by uchennaanya

- Here I
- scaffolded the friendship model
- Established relations between users
- And generated routes
- And also generated controllers

2021-03-25 15:02 UTC, oloomoses requested changes
## Changes Required :recycle: 
Hello team, you are doing great on this project so far. :muscle: 

### Highlights
- Great Job on the linter and rubocop configuration. :100: 

### Required changes
- [ ] Kindly remove logic from the views. Remember that views should be used only to display content from the controllers and not to generate them.
- [ ] The reject and accept friendship buttons are not working properly. When the `Accept Friend Request` button is clicked, the `Reject Friend Request` should not be seen
- [ ]  When the `Reject Friend Request` button is clicked, the `invite friend` button should be displayed
- [ ] The is a form to edit friendship in `All friends link` when a request is made. I don't think this is necessary, you can remove it.
- [ ] Kindly ensure that  posts timeline includes posts written by logged-in user and their friends as per the requirements
- [ ] Ensure that you add unit and integration tests for the app.

### Optional
- [ ] It would be better to style your buttons for a better user experience

Kindly implement the above changes before submitting another review.

**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

2021-03-25 15:02 UTC, oloomoses commented on app/views/users/_user.html.erb
> +  <% end %>
Kindly remove the logic from the view and move them into helpers.

2021-03-25 15:02 UTC, oloomoses commented on app/views/users/show.html.erb
> +  <% end %></p>
Kindly remove the logic from the view and put them into helpers

2021-04-11 01:35 UTC, cyonii requested changes
### STATUS: CHANGES REQUIRED ♻️✍️
Hello @uchennaanya, thank you for improving the project since the last review.

#### TO HIGHLIGHT
- Great job adding unit tests

#### TO IMPROVE
So far so well, however, there are still a few issues that needs to be fixed in order to meet this project's requirements.
- [x] As the previous pointed out, please remove all logic from your view, use helper methods to handle logic. Your view should be only responsible for displaying data. Check inline comments.
- [x] As pointed out previously your Reject Friend Request button is not functioning. I should be able to reject requests ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49736080/))
- [x] As previously requested, I should be able to see the Invite friend button after I reject their friendship request
- [x] Ensure  the timeline includes the logged-in user's post and those of their confirmed friends. Right now anyone can see any post without restrictopn. Please fix this.

#### NICE TO HAVE (Optional)
- [ ] I am able to send friendship request to my own self in the `User#show` view, you would agree this doesn't make much sense. You should validate your friendship model so that `user_id` and `friend_id` are unique together. I also should not see the Invite Friend button when am viewing my profile.

Having fun coding, keep your head high.

> #### <br>You can ping me on Slack @[CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) to draw my attention in case I do not respond quickly on here. I'm always available and will be glad to help.<br><br>

2021-04-11 01:35 UTC, cyonii commented on app/views/users/_user.html.erb
> +  <% end %>
No logic should be found on your views, please use helper methods instead

2021-04-11 01:35 UTC, cyonii commented on app/views/users/show.html.erb
> +  <% end %></p>
Remove these logic here please

2021-04-19 18:56 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @uchennaanya :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your milestone is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] There are still logics in your views, please make sure that there are no if conditions nor loops in your `.html.erb`
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-04-19 22:55 UTC, MahmoudBakr23 requested changes
# **Changes Required 🛑♻**

<hr>

Hello there :)
I can see you're making a lot of work and effort into this project. Please keep up the great work. However, I'm afraid you haven't made any changes since the last review you received. Kindly make sure to apply the requested changes before you ask for another CRR. 👍 

<hr>

Good luck and happy coding 💻👨‍💻

2021-04-21 05:15 UTC, jubaan requested changes
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>
<!-- BEGIN Awesome work -->

<!-- END Awesome work  -->
</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="open">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>
<!-- BEGIN Review -->

- [ ] Please remove the logic and loops from views (this includes partials)

<!-- END Review -->
</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>
<!-- BEGIN Optional and Comments -->

- [ ] Nothing more to add.

<!-- END Optional and Comments -->
</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    <img src="https://avatars.githubusercontent.com/u/25774518?s=400&u=ae20ddf2d6fb3cae9e2f4044afe3b93d19e5b69e&v=4" alt="Julio Añoveros" title="@jubaan" width="100px" heigh="100px"/>
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> <img src="https://www.pinclipart.com/picdir/big/130-1305924_rubber-ducky-clipart-eastern-iowa-duck-race-duck.png" width="18px" height="18px">... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

2021-04-21 06:19 UTC, mimipeshy commented
## STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello @uchennaanya 👋🏾 you have made such great progress in this milestone. Good job in working on the TSE feedback given. However, before approval make one more change  ⬇️ 

- [ ] There is still some logic and loops from your views, make use of [ helper methods](https://www.rubyguides.com/2020/01/rails-helpers/) whose function is to extract logic from views and controllers, keeping them lean


That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

2021-04-21 06:21 UTC, mimipeshy commented on app/views/users/_user.html.erb
> +    class: 'profile-link' %>
-Do not use loops inside views. Kindly use helpers for this.

2021-04-21 06:23 UTC, mimipeshy commented on app/views/friendships/index.html.erb
> +
- There should be absolutely no logic in views

2021-04-22 09:18 UTC, mimipeshy commented
## STATUS: APPROVED 🥳 👯 

Hello there @uchennaanya 👋🏾 👋🏾 great job so far on this milestone, you really have come a long way and you should be proud of yourself. You have worked on the changes requested and that is good of you 👏🏾

**[Optional]**

- [ ] It would be nice if you went through these articles to give you a clearer understanding of [helpers](https://www.rubyguides.com/2020/01/rails-helpers/), and how they can be used to make your code clean. Also, [where do I put my code](http://codefol.io/posts/Where-Do-I-Put-My-Code/) is a good article to read too, it explains how the rails structure works. 

 With that I  approve of this project, go ahead and merge. All the best in the next milestones

Regards
Peris Ndanu

2021-04-22 10:11 UTC, mimipeshy commented on app/views/friendships/_index.html.erb
> +  <% end %>
Kindly remove logic from your views. Logic includes loops and if statements. This will ensure your project follows the MVC pattern. You can create all your logic inside the helpers. ⬇️
Kindly use this article to learn more about this.[ Article](http://codefol.io/posts/Where-Do-I-Put-My-Code/)

2021-04-26 07:45 UTC, merged