PR For Third Milestone
uchennaanya/ror-social-scaffold pull request #3
Opened 2021-05-07 16:30 UTC by uchennaanya

# Here I
. Modified user model 
. Modified the friendship model

2021-05-07 18:51 UTC, sinansevgi requested changes
# Status: Changes Required :recycle: 

---------

Hello @uchennaanya,

You've made huge progress in this milestone. The way you defined reverse friendship shows that you understand the concept well. 

There are some changes are you should check before the project can be approved. Please check my comments below.

-------------
- [ ] You should only consider accepted friends as friends
```ruby
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships
```

- [ ] The timeline should include posts written by the user and their accepted friends.
At the moment, the timeline also displays posts of users with pending friend requests. (When I send a friend request to someone their posts becomes visible to me without their approval)

- [ ]  You should not have application logic in the **views** nor **helpers**. Everything connected with data processing should be encapsulated in models and used in controllers. Please remove logic from your view files. (_user, application_helper(Like.find_by query), users_helper( Friendship.where query)) 
 __View-related__ logic can be encapsulated in View helpers 


Please make these changes and request another code review. 
Happy Hacking

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

2021-05-07 18:51 UTC, sinansevgi commented on app/models/user.rb
> +  # end
- [x] Please remove commented-out code blocks.

2021-05-07 18:51 UTC, sinansevgi commented on app/models/user.rb
> +  end
- [ ]  User#pending_friends, User#pending_friendship methods can be defined as association with SQL query instead of processing friendships objects in application memory 

_(querying the database always more efficient than querying ruby objects)_

2021-05-28 23:40 UTC, enaburekhan requested changes
# Status: Changes required:wrench::hammer::full_moon:
**Hi Anya!
Great job on this project:clap::clap:. We are almost there. We just need to make a few changes to get the project approved:muscle:.**

**To improve**

- [ ] Check my inline comments below and make the required changes.

Request another review when you are ready.

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-05-28 23:40 UTC, enaburekhan commented on app/models/user.rb
> +  # end
- [ ] As earlier highlighted by the last reviewer. Kindly remove the commented codes. It makes the codebase to be untidy, difficult to read and understand. Use git history if you must review previous codes.

2021-05-28 23:40 UTC, enaburekhan commented on app/models/user.rb
> +  end
- [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
Use the above SQL query. Instead of the current ruby method. The reason, as already stated above:blush:

2021-05-29 00:51 UTC, enaburekhan approved these changes
# Status: Approve:heavy_check_mark:
**Hi Anya!
Congratulations:clap::clap:. Thank you for implementing all the changes earlier requested.
Move on with the next milestone:walking:. And don't forget to merge the PR and submit a project completion form.**

Do have questions/comments? kindly drop them :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan.

2021-05-29 07:55 UTC, merged